name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install -y build-essential libreadline8 libreadline-dev
    - name: clean
      run: make clean
    - name: make
      run: make
