name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: sudo apt install -y build-essential libreadline8 libreadline-dev
      - name: clean
        run: make clean
      - name: make
        run: make release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
